onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  ajv@<6.12.3: '>=6.12.3'
  body-parser@<1.20.3: '>=1.20.3'
  cookie@<0.7.0: '>=0.7.0'
  express@<4.19.2: '>=4.19.2'
  express@<4.20.0: '>=4.20.0'
  jsonwebtoken@<9.0.0: '>=9.0.0'
  jsonwebtoken@<=8.5.1: '>=9.0.0'
  jws@<3.2.3: '>=3.2.3'
  lodash@<4.17.11: '>=4.17.11'
  lodash@<4.17.12: '>=4.17.12'
  lodash@<4.17.21: '>=4.17.21'
  lodash@>=3.7.0 <4.17.19: '>=4.17.19'
  lodash@>=4.0.0 <4.17.21: '>=4.17.21'
  lodash@>=4.7.0 <4.17.11: '>=4.17.11'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  moment@<2.29.2: '>=2.29.2'
  moment@>=2.18.0 <2.29.4: '>=2.29.4'
  on-headers@<1.1.0: '>=1.1.0'
  path-to-regexp@<0.1.10: '>=0.1.10'
  path-to-regexp@<0.1.12: '>=0.1.12'
  qs@>=6.5.0 <6.5.3: '>=6.5.3'
  send@<0.19.0: '>=0.19.0'
  serve-static@<1.16.0: '>=1.16.0'
  ws@>=6.0.0 <6.2.2: '>=6.2.2'
  ws@>=6.0.0 <6.2.3: '>=6.2.3'
